/**
 * Token generator — the single source of truth (the TS tokens) emits two
 * consumable forms (06-Design-system.md §3):
 *   1. css/theme.css  — CSS custom properties on :root (the theming contract)
 *   2. preset.cjs     — the Tailwind preset (colors reference the CSS vars)
 *
 * Run with:  npm run generate  (tsx scripts/generate.ts)
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  colors,
  typography,
  spacing,
  radius,
  shadows,
  motion,
  breakpoints,
  layout,
  controlHeight,
  borderWidth,
  zIndex,
} from '../src/tokens/index';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(__dirname, '..');

/** Convert `#rrggbb` to a space-separated `r g b` channel triple. */
function toChannels(hex: string): string {
  const h = hex.replace('#', '');
  const r = parseInt(h.slice(0, 2), 16);
  const g = parseInt(h.slice(2, 4), 16);
  const b = parseInt(h.slice(4, 6), 16);
  return `${r} ${g} ${b}`;
}

/** Flat map of `--ds-*` custom properties (channel triples for colors). */
const vars: Record<string, string> = {};

for (const [shade, hex] of Object.entries(colors.primary)) {
  vars[`--ds-primary-${shade}`] = toChannels(hex);
}
for (const [shade, hex] of Object.entries(colors.neutral)) {
  vars[`--ds-neutral-${shade}`] = toChannels(hex);
}
for (const [name, hex] of Object.entries(colors.semantic)) {
  vars[`--ds-${name}`] = toChannels(hex);
}
vars['--ds-surface'] = toChannels(colors.surface.DEFAULT);
vars['--ds-surface-subtle'] = toChannels(colors.surface.subtle);
vars['--ds-surface-muted'] = toChannels(colors.surface.muted);
vars['--ds-canvas'] = toChannels(colors.surface.canvas);
vars['--ds-ink'] = toChannels(colors.ink.DEFAULT);
vars['--ds-ink-muted'] = toChannels(colors.ink.muted);
vars['--ds-ink-subtle'] = toChannels(colors.ink.subtle);
vars['--ds-border'] = toChannels(colors.border.DEFAULT);
vars['--ds-border-strong'] = toChannels(colors.border.strong);
vars['--ds-link'] = toChannels(colors.link);
for (const [name, pair] of Object.entries(colors.tint)) {
  vars[`--ds-tint-${name}-bg`] = toChannels(pair.bg);
  vars[`--ds-tint-${name}-fg`] = toChannels(pair.fg);
}
/** The single focus-visible ring color. */
vars['--ds-focus'] = toChannels(colors.primary[500]);

// Non-color design vars (kept as-is).
vars['--ds-overlay'] = colors.overlay;
vars['--ds-font-sans'] = typography.fontFamily.base;
vars['--ds-transition'] = motion.transition.base;

/* -------------------------------------------------------------------------- */
/* 1. theme.css                                                               */
/* -------------------------------------------------------------------------- */

const cssLines = Object.entries(vars)
  .map(([k, v]) => `  ${k}: ${v};`)
  .join('\n');

const themeCss = `/**
 * ReadyPH design tokens — CSS custom properties (the theming contract).
 *
 * GENERATED by scripts/generate.ts — do not edit by hand.
 *
 * Colors are stored as space-separated RGB channels so Tailwind opacity
 * utilities work: \`rgb(var(--ds-primary-500) / <alpha-value>)\`.
 *
 * Override any variable to retheme — globally, or scoped to a class /
 * [data-theme] — without rebuilding:
 *   .project-x { --ds-primary-500: 230 100 20; }
 */
:root {
${cssLines}
}

/* Base surface + ink for the document. Opt-in: apply to <body> or a root node. */
.ds-root,
body.ds-root {
  background-color: rgb(var(--ds-canvas));
  color: rgb(var(--ds-ink));
  font-family: var(--ds-font-sans);
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

/* Single focus-visible treatment across interactive components. */
.ds-focus-ring:focus-visible {
  outline: 2px solid rgb(var(--ds-focus));
  outline-offset: 2px;
}

/* Honor the user's motion preference everywhere. */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;

writeFileSync(resolve(pkgRoot, 'css/theme.css'), themeCss);

/* -------------------------------------------------------------------------- */
/* 2. preset.cjs                                                              */
/* -------------------------------------------------------------------------- */

/** `rgb(var(--x) / <alpha-value>)` wrapper so opacity utilities work. */
const c = (name: string) => `rgb(var(${name}) / <alpha-value>)`;

const scale = (prefix: string, obj: Record<string, unknown>) =>
  Object.fromEntries(Object.keys(obj).map((k) => [k, c(`--ds-${prefix}-${k}`)]));

const colorTheme = {
  transparent: 'transparent',
  current: 'currentColor',
  white: '#ffffff',
  black: '#000000',
  primary: scale('primary', colors.primary),
  neutral: scale('neutral', colors.neutral),
  success: c('--ds-success'),
  warning: c('--ds-warning'),
  error: c('--ds-error'),
  info: c('--ds-info'),
  surface: {
    DEFAULT: c('--ds-surface'),
    subtle: c('--ds-surface-subtle'),
    muted: c('--ds-surface-muted'),
    canvas: c('--ds-canvas'),
  },
  ink: {
    DEFAULT: c('--ds-ink'),
    muted: c('--ds-ink-muted'),
    subtle: c('--ds-ink-subtle'),
  },
  border: {
    DEFAULT: c('--ds-border'),
    strong: c('--ds-border-strong'),
  },
  link: c('--ds-link'),
  focus: c('--ds-focus'),
  tint: Object.fromEntries(
    Object.keys(colors.tint).flatMap((name) => [
      [`${name}-bg`, c(`--ds-tint-${name}-bg`)],
      [`${name}-fg`, c(`--ds-tint-${name}-fg`)],
    ]),
  ),
};

const preset = {
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: colorTheme,
      borderColor: { DEFAULT: c('--ds-border') },
      fontFamily: { sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'sans-serif'] },
      fontSize: typography.fontSize,
      fontWeight: typography.fontWeight,
      lineHeight: typography.lineHeight,
      spacing,
      borderRadius: radius,
      boxShadow: shadows,
      screens: breakpoints,
      zIndex: Object.fromEntries(Object.entries(zIndex).map(([k, v]) => [k, String(v)])),
      borderWidth: { DEFAULT: borderWidth.thin, thick: borderWidth.thick },
      transitionTimingFunction: { standard: motion.easing.standard },
      transitionDuration: {
        fast: motion.duration.fast,
        DEFAULT: motion.duration.base,
        slow: motion.duration.slow,
      },
      height: controlHeight,
      width: {
        rail: layout.railWidth,
        sidebar: layout.sidebarWidth,
        'right-panel': layout.rightPanelWidth,
      },
      maxWidth: { content: layout.contentMaxWidth },
      ringColor: { DEFAULT: c('--ds-focus') },
      backgroundColor: { overlay: 'var(--ds-overlay)' },
    },
  },
};

const presetCjs = `/**
 * ReadyPH Tailwind preset.
 *
 * GENERATED by scripts/generate.ts — do not edit by hand.
 *
 * Usage in a consuming Tailwind config:
 *   presets: [require('@readyph/design-tokens/preset')]
 * and add the UI package to \`content\` so its classes compile.
 */
/** @type {import('tailwindcss').Config} */
module.exports = ${JSON.stringify(preset, null, 2)};
`;

writeFileSync(resolve(pkgRoot, 'preset.cjs'), presetCjs);

// eslint-disable-next-line no-console
console.log('✓ generated css/theme.css and preset.cjs');
