/**
 * ReadyPH Tailwind preset.
 *
 * GENERATED by scripts/generate.ts — do not edit by hand.
 *
 * Usage in a consuming Tailwind config:
 *   presets: [require('@readyph/ui/preset')]
 * and add the UI package to `content` so its classes compile.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  "darkMode": [
    "class",
    "[data-theme=\"dark\"]"
  ],
  "theme": {
    "extend": {
      "colors": {
        "transparent": "transparent",
        "current": "currentColor",
        "white": "#ffffff",
        "black": "#000000",
        "primary": {
          "50": "rgb(var(--ds-primary-50) / <alpha-value>)",
          "100": "rgb(var(--ds-primary-100) / <alpha-value>)",
          "200": "rgb(var(--ds-primary-200) / <alpha-value>)",
          "300": "rgb(var(--ds-primary-300) / <alpha-value>)",
          "400": "rgb(var(--ds-primary-400) / <alpha-value>)",
          "500": "rgb(var(--ds-primary-500) / <alpha-value>)",
          "600": "rgb(var(--ds-primary-600) / <alpha-value>)",
          "700": "rgb(var(--ds-primary-700) / <alpha-value>)",
          "800": "rgb(var(--ds-primary-800) / <alpha-value>)",
          "900": "rgb(var(--ds-primary-900) / <alpha-value>)"
        },
        "neutral": {
          "50": "rgb(var(--ds-neutral-50) / <alpha-value>)",
          "100": "rgb(var(--ds-neutral-100) / <alpha-value>)",
          "200": "rgb(var(--ds-neutral-200) / <alpha-value>)",
          "300": "rgb(var(--ds-neutral-300) / <alpha-value>)",
          "400": "rgb(var(--ds-neutral-400) / <alpha-value>)",
          "500": "rgb(var(--ds-neutral-500) / <alpha-value>)",
          "600": "rgb(var(--ds-neutral-600) / <alpha-value>)",
          "700": "rgb(var(--ds-neutral-700) / <alpha-value>)",
          "800": "rgb(var(--ds-neutral-800) / <alpha-value>)",
          "900": "rgb(var(--ds-neutral-900) / <alpha-value>)"
        },
        "success": "rgb(var(--ds-success) / <alpha-value>)",
        "warning": "rgb(var(--ds-warning) / <alpha-value>)",
        "error": "rgb(var(--ds-error) / <alpha-value>)",
        "info": "rgb(var(--ds-info) / <alpha-value>)",
        "surface": {
          "DEFAULT": "rgb(var(--ds-surface) / <alpha-value>)",
          "subtle": "rgb(var(--ds-surface-subtle) / <alpha-value>)",
          "muted": "rgb(var(--ds-surface-muted) / <alpha-value>)",
          "canvas": "rgb(var(--ds-canvas) / <alpha-value>)"
        },
        "ink": {
          "DEFAULT": "rgb(var(--ds-ink) / <alpha-value>)",
          "muted": "rgb(var(--ds-ink-muted) / <alpha-value>)",
          "subtle": "rgb(var(--ds-ink-subtle) / <alpha-value>)"
        },
        "border": {
          "DEFAULT": "rgb(var(--ds-border) / <alpha-value>)",
          "strong": "rgb(var(--ds-border-strong) / <alpha-value>)"
        },
        "link": "rgb(var(--ds-link) / <alpha-value>)",
        "focus": "rgb(var(--ds-focus) / <alpha-value>)",
        "tint": {
          "peach-bg": "rgb(var(--ds-tint-peach-bg) / <alpha-value>)",
          "peach-fg": "rgb(var(--ds-tint-peach-fg) / <alpha-value>)",
          "green-bg": "rgb(var(--ds-tint-green-bg) / <alpha-value>)",
          "green-fg": "rgb(var(--ds-tint-green-fg) / <alpha-value>)",
          "teal-bg": "rgb(var(--ds-tint-teal-bg) / <alpha-value>)",
          "teal-fg": "rgb(var(--ds-tint-teal-fg) / <alpha-value>)",
          "gray-bg": "rgb(var(--ds-tint-gray-bg) / <alpha-value>)",
          "gray-fg": "rgb(var(--ds-tint-gray-fg) / <alpha-value>)"
        }
      },
      "borderColor": {
        "DEFAULT": "rgb(var(--ds-border) / <alpha-value>)"
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "'Segoe UI'",
          "sans-serif"
        ]
      },
      "fontSize": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem"
      },
      "fontWeight": {
        "light": 300,
        "normal": 400,
        "medium": 500,
        "semibold": 600,
        "bold": 700
      },
      "lineHeight": {
        "tight": 1.2,
        "snug": 1.375,
        "normal": 1.5,
        "relaxed": 1.625,
        "loose": 2
      },
      "spacing": {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
        "px": "1px",
        "0.5": "0.125rem",
        "1.5": "0.375rem",
        "2.5": "0.625rem",
        "3.5": "0.875rem"
      },
      "borderRadius": {
        "none": "0",
        "sm": "0.25rem",
        "base": "0.375rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.625rem",
        "2xl": "0.875rem",
        "full": "9999px"
      },
      "boxShadow": {
        "none": "none",
        "sm": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        "base": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
        "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
        "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
        "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)"
      },
      "screens": {
        "xs": "320px",
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px"
      },
      "zIndex": {
        "dropdown": "30",
        "drawer": "40",
        "modal": "50",
        "popover": "55",
        "toast": "60",
        "tooltip": "70"
      },
      "borderWidth": {
        "DEFAULT": "1px",
        "thick": "2px"
      },
      "transitionTimingFunction": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)"
      },
      "transitionDuration": {
        "fast": "100ms",
        "DEFAULT": "150ms",
        "slow": "250ms"
      },
      "height": {
        "sm": "2rem",
        "md": "2.25rem",
        "lg": "2.5rem"
      },
      "width": {
        "rail": "3.5rem",
        "sidebar": "15rem",
        "right-panel": "18rem"
      },
      "maxWidth": {
        "content": "48rem"
      },
      "ringColor": {
        "DEFAULT": "rgb(var(--ds-focus) / <alpha-value>)"
      },
      "backgroundColor": {
        "overlay": "var(--ds-overlay)"
      }
    }
  }
};
